### ISSUE TITLE
ToolBox compilation fails in 2.12

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#101]
```
[info] SemanticTests:
[info] scalafix.SemanticTests *** ABORTED *** (1 millisecond)
[info]   metaconfig.FailedToReadClass: Failed to read 'ScalafixConfig'. Errors: scala.tools.reflect.ToolBoxError: reflective compilation has failed:
[info]
[info] Error while emitting <no source file>
[info] assertion failed:
[info]   Cannot create ClassBType from NoSymbol
[info]      while compiling: <no file>
[info]         during phase: jvm
[info]      library version: version 2.12.1
[info]     compiler version: version 2.12.1
[info]   reconstructed args:
[info]
[info]   last tree to typer: TypeTree(object __wrapper$1$4e604d538a4c404892c2ba044dcb7068$MyRewrite2$2)
[info]        tree position: line 17 of <toolbox>
[info]             tree tpe: __wrapper$1$4e604d538a4c404892c2ba044dcb7068.__wrapper$1$4e604d538a4c404892c2ba044dcb7068$MyRewrite2$2.type
[info]               symbol: case object __wrapper$1$4e604d538a4c404892c2ba044dcb7068$MyRewrite2$2 in package __wrapper$1$4e604d538a4c404892c2ba044dcb7068
[info]    symbol definition: case class __wrapper$1$4e604d538a4c404892c2ba044dcb7068$MyRewrite2$2 extends Rewrite with Product with Serializable (a ModuleClassSymbol with SynchronizedModuleClassSymbol)
[info]       symbol package: __wrapper$1$4e604d538a4c404892c2ba044dcb7068
[info]        symbol owners: object __wrapper$1$4e604d538a4c404892c2ba044dcb7068$MyRewrite2$2
[info]            call site: constructor __wrapper$1$4e604d538a4c404892c2ba044dcb7068$MyRewrite2$2 in object __wrapper$1$4e604d538a4c404892c2ba044dcb7068$MyRewrite2$2 in package __wrapper$1$4e604d538a4c404892c2ba044dcb7068
[info]
[info] <Cannot read source file>
[info] Error while emitting <no source file>
[info] assertion failed: ClassBType.info not yet assigned: Lscala/meta/Term$Name;
[info]   at scalafix.config.ScalafixConfig$$anon$1.read(ScalafixConfig.scala:23)
[info]   at metaconfig.hocon.Hocon2Class$.$anonfun$gimmeClass$1(Hocon2Class.scala:45)
```

**Comment by olafurpg** [comment]
#127 added a new module scalafix-reflect that constructs a custom Scala global instead of using toolbox. This approach is a lot more robust, and avoid the need for the flaky instrumentation  (e.g., remove Pkg) to please toolbox.
