### ISSUE TITLE
 sbt-scalafix doesn't respect sbt.override.build.repos

### ISSUE THREAD

**Issue by sideeffffect** [scalacenter/scalafix#1049]
That means `sbt.repository.config` repositories don't get used and the build in a closed environment behind a caching proxy like Nexus or Artifactory fails, because it can't download scalafix

```
[Step 1/1] [error] coursierapi.error.SimpleResolutionError$1: Error downloading ch.epfl.scala:scalafix-cli_2.12.10:0.9.11
[Step 1/1] [error]   not found: /root/.ivy2/local/ch.epfl.scala/scalafix-cli_2.12.10/0.9.11/ivys/ivy.xml
[Step 1/1] [error]   download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-cli_2.12.10/0.9.11/scalafix-cli_2.12.10-0.9.11.pom
[Step 1/1] [error]   download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://oss.sonatype.org/content/repositories/releases/ch/epfl/scala/scalafix-cli_2.12.10/0.9.11/scalafix-cli_2.12.10-0.9.11.pom
[Step 1/1] [error]   download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://oss.sonatype.org/content/repositories/snapshots/ch/epfl/scala/scalafix-cli_2.12.10/0.9.11/scalafix-cli_2.12.10-0.9.11.pom
[Step 1/1] [error] 	at coursierapi.error.SimpleResolutionError.of(SimpleResolutionError.java:11)
[Step 1/1] [error] 	at coursierapi.shaded.coursier.internal.api.ApiHelper$.simpleResError(ApiHelper.scala:324)
[Step 1/1] [error] 	at coursierapi.shaded.coursier.internal.api.ApiHelper$.doFetch(ApiHelper.scala:357)
[Step 1/1] [error] 	at coursierapi.shaded.coursier.internal.api.ApiHelper.doFetch(ApiHelper.scala)
[Step 1/1] [error] 	at coursierapi.Fetch.fetchResult(Fetch.java:244)
[Step 1/1] [error] 	at coursierapi.Fetch.fetch(Fetch.java:239)
[Step 1/1] [error] 	at scalafix.internal.sbt.ScalafixCoursier$.runFetch(ScalafixCoursier.scala:88)
```
comparable to https://github.com/scalameta/sbt-scalafmt/issues/62

setting `COURSIER_REPOSITORIES` env variable doesn't help

setting `ThisBuild / scalafixResolvers` works around this issue

**Comment by bjaglin** [comment]
related discussion https://github.com/scalacenter/sbt-scalafix/pull/292#discussion_r834283114

**Comment by bjaglin** [comment]
should be fixed by https://github.com/scalacenter/sbt-scalafix/pull/404
