### ISSUE TITLE
Scala fix fails to run on test

### ISSUE THREAD

**Issue by daddykotex** [scalacenter/scalafix#1110]
Hi, thanks for the project, it's truly helpful!

I'm working hard to add this as part of our CI but I can't figure out why I can't run it against our test sources. At first I thought it might be the dependency on scalatest, but it's not. A very dummy repo reproduces:

https://github.com/daddykotex/scalafix-issue-repro

```
sbt 1.3.10
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.15")
scala := 2.13.1
```

I'm getting a bunch of error when I run `test:scalafix --check`:

```
[info] Compiling 1 Scala source to /Users/david/workspace/scalafix-test/module1/target/scala-2.13/test-classes ...
[warn] there was one deprecation warning (since 2.13.0); re-run with -deprecation for details
[warn] one warning found
java.io.IOException: Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in package.class
	at scala.reflect.internal.pickling.UnPickler$Scan.checkVersion(UnPickler.scala:124)
	at scala.reflect.internal.pickling.UnPickler$Scan.<init>(UnPickler.scala:66)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:47)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.unpickleOrParseInnerClasses(ClassfileParser.scala:1176)
  | => mat scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:465)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$2(ClassfileParser.scala:161)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:146)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:129)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:329)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:230)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1539)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:355)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:410)
	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:299)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:230)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1539)
	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2285)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.init(FindMembers.scala:36)
	at scala.reflect.internal.tpe.FindMembers$FindMember.init(FindMembers.scala:255)
	at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1040)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1039)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1044)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:673)
.....

MULTIPLE PAGES OF THAT
```

Any idea what I'm doing wrong?

Thanks, again

**Comment by bjaglin** [comment]
I ran into something similar, thanks for the repro!

I narrowed the problem: when a semanticdb compiler parameter is repeated, scalafix picks the first occurence, while the compiler picks the last.

```
sbt:hello-world> show module1/Test/scalacOptions
[info] * -Ywarn-unused
[info] * -Xplugin:/home/bjaglin/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.1/4.3.8/semanticdb-scalac_2.13.1-4.3.8.jar
[info] * -Yrangepos
[info] * -P:semanticdb:targetroot:/home/bjaglin/git/projects/scalafix-issue-repro/module1/target/scala-2.13/meta
[info] * -P:semanticdb:targetroot:/home/bjaglin/git/projects/scalafix-issue-repro/module1/target/scala-2.13/test-meta
```

I'll open a PR shortly.

**Comment by daddykotex** [comment]
Ahh thank you very much.
