### ISSUE TITLE
Running scalafix CLI gives confusing errors

### ISSUE THREAD

**Issue by jqno** [scalacenter/scalafix#1205]
I'm trying to run the [`OrganizeImports`](https://github.com/liancheng/scalafix-organize-imports) plugin from the CLI, but I keep getting errors:

```
error: error while loading Object, Missing dependency 'object scala.native in compiler mirror', required by /modules/java.base/java/lang/Object.class
error: SemanticDB not found: src/main/scala/my/package/Something.scala
```

This is how I try to run the command:

```
$ scalafix \
  --tool-classpath $(cs fetch com.github.liancheng:organize-imports_2.13:0.3.1-RC3 -p) \
  --scalac-options -Ywarn-unused \
  --rules OrganizeImports \
  --classpath target/classes
  --files src/main/scala/my/package/Something.scala
```

If I try to run the same commandline, but for `organize-imports_2.12`, I get a stacktrace:

```
Exception in thread "main" java.util.ServiceConfigurationError: scalafix.v1.Rule: Provider fix.OrganizeImports could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.next(JavaCollectionWrappers.scala:38)
	at scala.collection.immutable.List.prependedAll(List.scala:156)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1258)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1258)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1279)
	at scalafix.internal.v1.Rules$.all(Rules.scala:101)
	at scalafix.v1.RuleDecoder$$anon$1.<init>(RuleDecoder.scala:99)
	at scalafix.v1.RuleDecoder$.decoder(RuleDecoder.scala:98)
	at scalafix.internal.v1.Args.ruleDecoder(Args.scala:242)
	at scalafix.internal.v1.Args.configuredRules(Args.scala:261)
	at scalafix.internal.v1.Args.$anonfun$validate$1(Args.scala:369)
	at metaconfig.Configured.andThen(Configured.scala:33)
	at scalafix.internal.v1.Args.validate(Args.scala:364)
	at scalafix.internal.v1.MainOps$.run(MainOps.scala:60)
	at scalafix.v1.Main$.run(Main.scala:32)
	at scalafix.v1.Main$.main(Main.scala:23)
	at scalafix.cli.Cli$.main(Cli.scala:9)
	at scalafix.cli.Cli.main(Cli.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'scala.collection.mutable.WrappedArray scala.Predef$.wrapRefArray(java.lang.Object[])'
	at fix.OrganizeImportsConfig$.apply$default$5(OrganizeImportsConfig.scala:56)
	at fix.OrganizeImportsConfig$.<init>(OrganizeImportsConfig.scala:64)
	at fix.OrganizeImportsConfig$.<clinit>(OrganizeImportsConfig.scala)
	at fix.OrganizeImports.<init>(OrganizeImports.scala:49)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 26 more
```

I'm using a scalafix 0.9.17 binary which I've installed using coursier.

I'm not sure how to proceed.

**Comment by olafurpg** [comment]
Thank you for reporting! This error message comes from the Scala compiler and it should be fixed if you update the `--classpath` argument to contain the full classpath of your project (including `scala-library.jar` and all library dependencies).

**Comment by jqno** [comment]
Thank you for the quick response! Indeed, it's not fast but it does work now 😄 

```
scalafix \
  --tool-classpath $(cs fetch com.github.liancheng:organize-imports_2.13:0.3.1-RC3 -p) \
  --scalac-options -Ywarn-unused \
  --rules OrganizeImports \
  --classpath $(mvn -q org.codehaus.mojo:exec-maven-plugin:exec -Dexec.classpathScope="compile" -Dexec.executable="echo" -Dexec.args="%classpath") \
  --files src/main/scala/my/package/Something.scala
```

(I was seeing some hype about this on twitter and figured, maybe I can run this from Vim. Looks like I can now, but maybe it's not quite ready for the limelight yet 😄)

**Comment by olafurpg** [comment]
I recommend using Scalafix from a build tool integration like sbt-scalafix/Maven/Gradle. It runs significantly faster when the JVM process is kept hot between invocations. The sbt-scalafix plugin supports incremental fixing + (soon) fix on compile thank to work by @bjaglin!

**Comment by jqno** [comment]
Thanks, that makes sense, and I'm glad to hear work is continuing so quickly on this cool project :)

Unfortunately, I'm the lone Vim user in our team; I'm not sure I can convince my team mates to add this to our `pom.xml`, at least not yet :). I'll try to see if I can configure Maven somehow to use a plugin that's not in the pom (perhaps through `~/.m2/settings.xml` but until then, I'm happy with this solution :).

**Comment by olafurpg** [comment]
You may be experiencing that Scalafix is extra slow because it needs to re-typecheck the source file if the `--classpath` argument doesn't include SemanticDB files for the sources to be fixed. It runs faster if the Maven build compiles with the SemanticDB compiler plugin enabled

**Comment by jqno** [comment]
Ah ok, I wasn't aware of this. Can you point me to a link that says how to add SemanticDB to Maven? I'm looking [here](https://scalameta.org/docs/semanticdb/guide.html) but can't find instructions for Maven.

And, thank you for continuing to help even though the issue is already closed. 😄

**Comment by olafurpg** [comment]
SemanticDB is a normal Scala compiler that can be enabled with the -Xplugin:JAR option. See https://scalameta.org/docs/semanticdb/guide.html#scalac-compiler-plugin 

You might able be able enjoy faster performance if you run Scalafix via nailgun
