### ISSUE TITLE
sbt-scalafix: Creating XDG_CONFIG_HOME directory <...> failed

### ISSUE THREAD

**Issue by oschrenk** [scalacenter/scalafix#1247]
I installed `sbt-scalafix` globally

```
cat ~/.sbt/1.0/plugins/sbt-scalafix.sbt
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.20")
```

On every sbt execution I get

```
14:30:47.087 [pool-37-thread-7] ERROR org.eclipse.jgit.util.SystemReader - Creating XDG_CONFIG_HOME directory /Users/oliver/.config failed
java.nio.file.FileAlreadyExistsException: /Users/oliver/.config
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:742) ~[?:?]
        at org.eclipse.jgit.util.SystemReader$Default.getXDGConfigHome(SystemReader.java:120) ~[?:?]
        at org.eclipse.jgit.util.SystemReader$Default.openJGitConfig(SystemReader.java:131) ~[?:?]
        at org.eclipse.jgit.util.SystemReader.getJGitConfig(SystemReader.java:348) ~[?:?]
        at org.eclipse.jgit.util.SystemReader.getSystemConfig(SystemReader.java:373) ~[?:?]
        at org.eclipse.jgit.util.SystemReader.getUserConfig(SystemReader.java:321) ~[?:?]
        at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:162) ~[?:?]
        at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:55) ~[?:?]
        at scalafix.internal.sbt.JGitCompletion.<init>(JGitCompletions.scala:24) ~[?:?]
        at scalafix.internal.sbt.ScalafixCompletions.gitDiffParser$lzycompute(ScalafixCompletions.scala:99) ~[?:?]
        at scalafix.internal.sbt.ScalafixCompletions.gitDiffParser(ScalafixCompletions.scala:98) ~[?:?]
        at scalafix.internal.sbt.ScalafixCompletions.parser(ScalafixCompletions.scala:167) ~[?:?]
        at scalafix.sbt.ScalafixPlugin$.$anonfun$scalafixInputTask$1(ScalafixPlugin.scala:318) ~[?:?]
        at scala.Function1.$anonfun$compose$1(Function1.scala:49) ~[scala-library.jar:?]
        at scala.Function1.$anonfun$compose$1(Function1.scala:49) ~[scala-library.jar:?]
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228) ~[collections_2.12-1.4.0-RC2.jar:1.4.0-RC2]
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170) ~[collections_2.12-1.4.0-RC2.jar:1.4.0-RC2]
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87) ~[collections_2.12-1.4.0-RC2.jar:1.4.0-RC2]
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99) [collections_2.12-1.4.0-RC2.jar:1.4.0-RC2]
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94) [collections_2.12-1.4.0-RC2.jar:1.4.0-RC2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

...
```

Tested with sbt 1.3.13, 1.4.0-RC2 on openjdk version "11.0.8" 2020-07-14 on macOS 10.15.6

**Comment by bjaglin** [comment]
This looks like https://bugs.eclipse.org/bugs/show_bug.cgi?id=565637, which was fixed in [`"org.eclipse.jgit" % "org.eclipse.jgit" % "5.8.1.202007141445-r"`](https://github.com/scalacenter/sbt-scalafix/pull/163/files) and thus should not be reproducible with 0.9.21.

Can you confirm @oschrenk ?

**Comment by oschrenk** [comment]
Confirmed. Works fine in 0.9.21
