### ISSUE TITLE
class scala.Serializable in compiler mirror not found.

### ISSUE THREAD

**Issue by ornicar** [scalacenter/scalafix#1366]
I'm trying to use scalafix for the lichess.org source code, [ornicar/lila](github.com/ornicar/lila).
Scalafix installation: https://github.com/ornicar/lila/pull/8607/files

No luck so far, as I'm getting a bunch of cryptic errors that I couldn't fix by googling around.

Steps to reproduce:

```
git clone https://github.com/ornicar/lila --branch scalafix
cd lila
sbt
project common
scalafix RemoveUnused
```

Result:
```
[/home/thib/lila/modules/common/src/main/base/Levenshtein.scala] marking unit as crashed (crashedFiles: Set(/home/thib/lila/modules/common/src/main/base/LilaException.scala, /home/thib/lila/modules/common/src/main/constants.scala, /home/thib/lila/modules/common/src/main/Cli.scala, /home/thib/lila/modules/common/src/main/log.scala, /home/thib/lila/modules/common/src/main/WMMatching.scala, /home/thib/lila/modules/common/src/main/Sequence.scala, /home/thib/lila/modules/common/src/main/LilaCookie.scala, /home/thib/lila/modules/common/src/main/Bus.scala, /home/thib/lila/modules/common/src/main/Json.scala, /home/thib/lila/modules/common/src/main/CuteNameGenerator.scala, /home/thib/lila/modules/common/src/main/ThreadLocalRandom.scala, /home/thib/lila/modules/common/src/main/PackageObject.scala, /home/thib/lila/modules/common/src/main/Nonce.scala, /home/thib/lila/modules/common/src/main/model.scala, /home/thib/lila/modules/common/src/main/WorkQueue.scala, /home/thib/lila/modules/common/src/main/paginator/Adapter.scala, /home/thib/lila/modules/common/src/main/Tellable.scala, /home/thib/lila/modules/common/src/main/Chronometer.scala, /home/thib/lila/modules/common/src/main/LilaCache.scala, /home/thib/lila/modules/common/src/main/paginator/Paginator.scala, /home/thib/lila/modules/common/src/main/Maths.scala, /home/thib/lila/modules/common/src/main/Form.scala, /home/thib/lila/modules/common/src/main/base/Levenshtein.scala, /home/thib/lila/modules/common/src/main/LameName.scala, /home/thib/lila/modules/common/src/main/Iso.scala, /home/thib/lila/modules/common/src/main/mon.scala, /home/thib/lila/modules/common/src/main/Lilaisms.scala, /home/thib/lila/modules/common/src/main/paginator/PaginatorJson.scala, /home/thib/lila/modules/common/src/main/config.scala, /home/thib/lila/modules/common/src/main/Lilakka.scala, /home/thib/lila/modules/common/src/main/Markdown.scala, /home/thib/lila/modules/common/src/main/Day.scala, /home/thib/lila/modules/common/src/main/base/PimpedPrimitives.scala, /home/thib/lila/modules/common/src/main/MultiKeyMap.scala, /home/thib/lila/modules/common/src/main/LilaStream.scala, /home/thib/lila/modules/common/src/main/ResilientScheduler.scala, /home/thib/lila/modules/common/src/main/Captcha.scala, /home/thib/lila/modules/common/src/main/Future.scala, /home/thib/lila/modules/common/src/main/Debouncer.scala, /home/thib/lila/modules/common/src/main/LightUser.scala, /home/thib/lila/modules/common/src/main/String.scala, /home/thib/lila/modules/common/src/main/Uptime.scala, /home/thib/lila/modules/common/src/main/Heapsort.scala, /home/thib/lila/modules/common/src/main/HTTPRequest.scala, /home/thib/lila/modules/common/src/main/GreatPlayer.scala, /home/thib/lila/modules/common/src/main/ContentSecurityPolicy.scala))
[/home/thib/lila/modules/common/src/main/base/RawHtml.scala]: exception during background compile: scala.reflect.internal.MissingRequirementError: class scala.Serializable in compiler mirror not found.
scala.reflect.internal.MissingRequirementError: class scala.Serializable in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:24)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:25)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$getModuleOrClass$5(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.requiredClass(Mirrors.scala:121)
	at scala.reflect.internal.Definitions$DefinitionsClass.SerializableClass$lzycompute(Definitions.scala:402)
	at scala.reflect.internal.Definitions$DefinitionsClass.SerializableClass(Definitions.scala:402)
	at scala.reflect.internal.Definitions$DefinitionsClass.isPossibleSyntheticParent$lzycompute(Definitions.scala:1453)
	at scala.reflect.internal.Definitions$DefinitionsClass.isPossibleSyntheticParent(Definitions.scala:1453)
	at scala.tools.nsc.typechecker.Typers$Typer.fixDuplicateSyntheticParents(Typers.scala:1684)
	at scala.tools.nsc.typechecker.Typers$Typer.typedParentTypes(Typers.scala:1694)
	at scala.tools.nsc.typechecker.Namers$Namer.templateSig(Namers.scala:1150)
	at scala.tools.nsc.typechecker.Namers$Namer.moduleSig(Namers.scala:1251)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1922)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1870)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:877)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2081)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2079)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2074)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1542)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1698)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5403)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5780)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5844)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3337)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3337)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5410)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5703)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5780)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:116)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
	at scala.tools.nsc.interactive.Global$TyperRun.$anonfun$applyPhase$1(Global.scala:1340)
	at scala.tools.nsc.interactive.Global$TyperRun.applyPhase(Global.scala:1340)
	at scala.tools.nsc.interactive.Global$TyperRun.typeCheck(Global.scala:1333)
	at scala.tools.nsc.interactive.Global.typeCheck(Global.scala:665)
	at scala.tools.nsc.interactive.Global.$anonfun$backgroundCompile$7(Global.scala:580)
	at scala.tools.nsc.interactive.Global.$anonfun$backgroundCompile$6(Global.scala:576)
	at scala.tools.nsc.interactive.Global.$anonfun$backgroundCompile$6$adapted(Global.scala:576)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:576)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:32)
```

I must be missing something obvious. Please help.

**Comment by bjaglin** [comment]
Thanks for the report and the repro steps - I can reproduce locally, and the first error is
```
[info] Running scalafix on 55 Scala sources
bad option: '-Ymacro-annotations'
```

**Comment by bjaglin** [comment]
What happens is that scalafix can't find semanticdb files, and thus tries to generate them on the fly, with the default scala version of sbt (2.12), thus the "Ymacro-annotations". It's possible to customize this version via `scalafixScalaBinaryVersion` but this would just work around the problem and result in a very long run time.

Under the hood, sbt-scalafix calls `compile`, and for some reason nothing happens, even when invoked explicitly (I also checked on master):
```
[lila] $ project common
[info] set current project to common (in build file:/home/bjaglin/git/projects/lila/)
sbt:common> compile
[success] Total time: 3 s, completed Apr 9, 2021, 11:22:49 AM
sbt:common> last compileIncremental
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[debug] current source = Set()
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] Full compilation, no sources in previous analysis.
sbt:common> 
```

Is that expected that `compile` does not have any side effect on `commons`?

**Comment by ornicar** [comment]
Thank you for looking into it. I'm surprised that `compile` does nothing there, nor in other subprojects or the root project.

We've been relying on bloop for some time now, so `compile` has not been run in a while.

**Comment by bjaglin** [comment]
https://github.com/ornicar/lila/commit/0c36b07cc14593c21b422ac01c621afd92c1eb19#diff-a7069678b490aad347fac8a256daeda5f83135c60bbec6239eebc507873baacaR25 looks suspicious

**Comment by ornicar** [comment]
Thank you so much for figuring that out! It's working now :)
