### ISSUE TITLE
`scalafix.sbt.InvalidArgument` error with 0.9.28 when using `include` in `.scalafix.conf`

### ISSUE THREAD

**Issue by therockstorm** [scalacenter/scalafix#1414]
I've updated to `sbt` 1.5.2, Scala 2.13.6, and `scalafix` 0.9.28 and am seeing this error when I try to run `scalafixAll`,

`scalafix.sbt.InvalidArgument: 8 is not a valid line number, allowed [0..7]`.

`.scalafix.conf`:

```
include ".scalafix-common.conf"
```

`.scalafix-common.conf`:

```
rules = [
  DisableSyntax
]

DisableSyntax {
  noAsInstanceOf = true
  noFinalVal = true
  noFinalize = true
  noXml = true
}
```

However, if I copy the configuration from `.scalafix-common.conf` directly into `.scalafix.conf`, it works fine.

**Comment by bjaglin** [comment]
Thanks for the report!

I can reproduce the issue with 0.9.28 in CLI:
```
Exception in thread "main" java.lang.IllegalArgumentException: 8 is not a valid line number, allowed [0..1]
	at metaconfig.Input.lineToOffset(Input.scala:36)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.$anonfun$getPositionOpt$2(TypesafeConfig2Class.scala:85)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.$anonfun$getPositionOpt$2$adapted(TypesafeConfig2Class.scala:83)
	at scala.Option.map(Option.scala:242)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.$anonfun$getPositionOpt$1(TypesafeConfig2Class.scala:83)
	at scala.Option.flatMap(Option.scala:283)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.getPositionOpt(TypesafeConfig2Class.scala:82)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.loop$1(TypesafeConfig2Class.scala:56)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.$anonfun$gimmeSafeConf$1(TypesafeConfig2Class.scala:39)
	at scala.collection.MapView$MapValues.$anonfun$iterator$1(MapView.scala:119)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
	at scala.collection.AbstractIterable.toList(Iterable.scala:919)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.loop$1(TypesafeConfig2Class.scala:39)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.$anonfun$gimmeSafeConf$1(TypesafeConfig2Class.scala:39)
	at scala.collection.MapView$MapValues.$anonfun$iterator$1(MapView.scala:119)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.immutable.List.prependedAll(List.scala:156)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
	at scala.collection.AbstractIterable.toList(Iterable.scala:919)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.loop$1(TypesafeConfig2Class.scala:39)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.gimmeSafeConf(TypesafeConfig2Class.scala:62)
	at metaconfig.typesafeconfig.TypesafeConfig2Class$.gimmeConfFromFile(TypesafeConfig2Class.scala:26)
	at metaconfig.Hocon$.fromInput(Hocon.scala:8)
	at metaconfig.Conf$.parseInput(Conf.scala:69)
	at scalafix.internal.v1.Args.fileConfig(Args.scala:236)
	at scalafix.internal.v1.Args.baseConfig(Args.scala:216)
	at scalafix.internal.v1.Args.validate(Args.scala:416)
	at scalafix.internal.v1.MainOps$.run(MainOps.scala:72)
	at scalafix.v1.Main$.run(Main.scala:34)
	at scalafix.v1.Main$.main(Main.scala:25)
	at scalafix.cli.Cli$.main(Cli.scala:9)
	at scalafix.cli.Cli.main(Cli.scala)
```

I assume it's related to the bump of metaconfig in https://github.com/scalacenter/scalafix/pull/1369. I'll see if I can create a repro to file a ticket there.

**Comment by bjaglin** [comment]
https://github.com/scalameta/metaconfig/pull/131

**Comment by bjaglin** [comment]
I just reverted the bump that caused the regression as I wanted to rush out a 2.12.14 release, so this should effectively be resolved in 0.9.29. I will follow up on https://github.com/scalameta/metaconfig/pull/131.

**Comment by therockstorm** [comment]
Thanks, @bjaglin!

**Comment by bjaglin** [comment]
@therockstorm [the actual fix](https://github.com/scalacenter/scalafix/pull/1419) (not the revert) is now merged to `main`. Would you mine confirming that it works for you by running the latest SNAPSHOT available, as documented in https://scalacenter.github.io/scalafix/docs/users/installation.html#snapshot?

**Comment by therockstorm** [comment]
Yes, it's still working for me using the latest snapshot.
