### ISSUE TITLE
Running scalafix on a project results in error Missing symbol local17

### ISSUE THREAD

**Issue by OndrejSpanel** [scalacenter/scalafix#1459]
When I run scalafix Collection213Upgrade on my project, I get following exception:

```text
[IJ]scalafix Collection213Upgrade
[info] compiling 282 Scala sources and 6 Java sources to xxxxxx\target\scala-2.12\classes ...
[info] done compiling
[info] Running scalafix on 282 Scala sources
[error] scalafix.internal.v1.FileException: unexpected error processing file xxxxx\xxxx.scala
[error] Caused by: scalafix.v1.MissingSymbolException: Missing symbol local17
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$2(LegacyCodePrinter.scala:81)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$2$adapted(LegacyCodePrinter.scala:73)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$mkString$1(LegacyCodePrinter.scala:48)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$mkString$1$adapted(LegacyCodePrinter.scala:42)
[error]         at scala.collection.immutable.List.foreach(List.scala:431)
[error]         at scalafix.internal.v0.LegacyCodePrinter.mkString(LegacyCodePrinter.scala:42)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$1(LegacyCodePrinter.scala:73)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$1$adapted(LegacyCodePrinter.scala:72)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scalafix.internal.v0.LegacyCodePrinter.pprint(LegacyCodePrinter.scala:72)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$4(LegacyCodePrinter.scala:100)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$4$adapted(LegacyCodePrinter.scala:100)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scalafix.internal.v0.LegacyCodePrinter.pprint(LegacyCodePrinter.scala:100)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$9(LegacyCodePrinter.scala:131)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$9$adapted(LegacyCodePrinter.scala:131)
[error]         at scala.Option.foreach(Option.scala:407)
[error]         at scalafix.internal.v0.LegacyCodePrinter.pprint(LegacyCodePrinter.scala:131)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$loop$4(LegacyCodePrinter.scala:203)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$loop$4$adapted(LegacyCodePrinter.scala:203)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$mkString$1(LegacyCodePrinter.scala:48)
[error]         at scalafix.internal.v0.LegacyCodePrinter.$anonfun$mkString$1$adapted(LegacyCodePrinter.scala:42)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scalafix.internal.v0.LegacyCodePrinter.mkString(LegacyCodePrinter.scala:42)
[error]         at scalafix.internal.v0.LegacyCodePrinter.loop(LegacyCodePrinter.scala:203)
[error]         at scalafix.internal.v0.LegacyCodePrinter.convertSynthetic(LegacyCodePrinter.scala:208)
[error]         at scalafix.internal.v0.LegacySemanticdbIndex$.syntheticToLegacy(LegacySemanticdbIndex.scala:171)
[error]         at scalafix.internal.v0.LegacySemanticdbIndex.$anonfun$synthetics$1(LegacySemanticdbIndex.scala:53)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at scalafix.internal.v0.LegacySemanticdbIndex.synthetics(LegacySemanticdbIndex.scala:52)
[error]         at scala.fix.collection.Stable212Base.replaceTo(Stable212Base.scala:289)
[error]         at scala.fix.collection.Stable212Base.replaceTo$(Stable212Base.scala:287)
[error]         at scala.fix.collection.Collection213UpgradeV0.replaceTo(Collection213Upgrade.scala:28)
[error]         at scala.fix.collection.Stable212Base.fix(Stable212Base.scala:596)
[error]         at scala.fix.collection.Stable212Base.fix$(Stable212Base.scala:593)
[error]         at scala.fix.collection.Collection213UpgradeV0.fix(Collection213Upgrade.scala:120)
[error]         at scalafix.internal.v0.LegacySemanticRule.fix(LegacySemanticRule.scala:29)
[error]         at scalafix.internal.v1.Rules.$anonfun$semanticPatch$1(Rules.scala:78)
[error]         at scala.collection.immutable.List.map(List.scala:293)
[error]         at scalafix.internal.v1.Rules.semanticPatch(Rules.scala:76)
[error]         at scalafix.internal.v1.MainOps$.getPatchesAndDiags(MainOps.scala:305)
[error]         at scalafix.internal.v1.MainOps$.unsafeHandleFile(MainOps.scala:255)
```

In another file I get the same callstack, only the symbol is different: `Missing symbol local74`.

I have no idea what is causing it and how could I fix it.

The project is closed source and quite large, I am afraid getting a small repro will be quite time consuming, but if it is deemed really necessary, I might try.

All other sources in the project got rewritten fine.

**Comment by mlachkar** [comment]
Hello, thanks for reporting this issue. I have a question: So the rule runs fine on the remaining files (except 2) ?

**Comment by OndrejSpanel** [comment]
Yes, most files in the project were rewritten fine. I think there were a few files with `collection.breakout` still present, which looked like they were rewritten only partially, but many files were rewritten fine, including `breakout` replaced with `.iterator` / `to(XXXX)` - and the `breakout` not replaced might be a separate issue anyway, this is hard to tell for me.

If you need any more information, I think I can checkout the same revision anytime, run it again and report anything you might be interested about.

**Comment by bjaglin** [comment]
Any chance you could take the smallest file that triggers the stack trace above and cut out / inline a stub of its dependencies to provide a snippet reproducing this behavior?

**Comment by OndrejSpanel** [comment]
> I am afraid getting a small repro will be quite time consuming, but if it is deemed really necessary, I might try.

I have personally no more interest in the issue, as I rewrote the rest of the files manually.

Still I will try and check what can be done, perhaps it will not be as bad as it seems.

**Comment by OndrejSpanel** [comment]
I am trying to create a small repro, but it is not going very smooth. I need to clean the project after each try, as otherwise I get some strange incremental compilation errors. Moreover, the file for which the exception is thrown does not contain any collection code which would need rewritten - it compiles without any issues or warnings as it is in 2.13.

It is hard to decide what code to delete so that the project still compiles and yet the error is thrown. Delete individual files or parts of them mechanically does not seem possible, as the code needs to be compilable for Collection213Upgrade to run on it.

**Comment by OndrejSpanel** [comment]
I have create a repro. It is one file, about 50 lines, and it requires one external open source library ([borer](https://github.com/sirthias/borer)).

I was unable to reduce it any more, in particular I was not successful in reproducing the issue without the Borer dependency.

Feel free to grab the project at https://github.com/OndrejSpanel/ScalaFix-repro

**Comment by will-sargent-eero** [comment]
I think I have the same problem:

```
[error] Caused by: scalafix.v1.MissingSymbolException: Missing symbol local106
[error] 	at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$2(LegacyCodePrinter.scala:81)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$2$adapted(LegacyCodePrinter.scala:73)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.$anonfun$mkString$1(LegacyCodePrinter.scala:48)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.$anonfun$mkString$1$adapted(LegacyCodePrinter.scala:42)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.mkString(LegacyCodePrinter.scala:42)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$1(LegacyCodePrinter.scala:73)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$1$adapted(LegacyCodePrinter.scala:72)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.pprint(LegacyCodePrinter.scala:72)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$4(LegacyCodePrinter.scala:100)
[error] 	at scalafix.internal.v0.LegacyCodePrinter.$anonfun$pprint$4$adapted(LegacyCodePrinter.scala:100)
```

**Comment by mberchon** [comment]
Hello

+1 

`[error] scalafix.internal.v1.FileException: unexpected error processing file /Users/math/MYCOM-WS/aiops-bda-spe-sandbox/bda-spe-spark/src/test/scala/com/mycomosi/bda/spe/spark/anomaly/objects/AnomalyObjectsSerDeTest.scala
[error] Caused by: scala.meta.internal.classpath.MissingSymbolException: missing symbol: org.scalameter
[error]         at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.descriptor(SymbolOps.scala:121)
[error]         at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.uncached$1(SymbolOps.scala:19)
[error]         at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.toSemantic(SymbolOps.scala:26)
[error]         at scala.meta.internal.scalacp.SymbolOps$XtensionSymbol.ssym(SymbolOps.scala:187)
[error]         at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.owner(SymbolOps.scala:59)
[error]         at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.uncached$1(SymbolOps.scala:19)
[error]         at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.toSemantic(SymbolOps.scala:26)
`

**Comment by mberchon** [comment]
> Hello
> 
> +1
> 
> `[error] scalafix.internal.v1.FileException: unexpected error processing file /Users/math/MYCOM-WS/aiops-bda-spe-sandbox/bda-spe-spark/src/test/scala/com/mycomosi/bda/spe/spark/anomaly/objects/AnomalyObjectsSerDeTest.scala [error] Caused by: scala.meta.internal.classpath.MissingSymbolException: missing symbol: org.scalameter [error] at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.descriptor(SymbolOps.scala:121) [error] at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.uncached$1(SymbolOps.scala:19) [error] at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.toSemantic(SymbolOps.scala:26) [error] at scala.meta.internal.scalacp.SymbolOps$XtensionSymbol.ssym(SymbolOps.scala:187) [error] at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.owner(SymbolOps.scala:59) [error] at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.uncached$1(SymbolOps.scala:19) [error] at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.toSemantic(SymbolOps.scala:26) `

I worked around my issue by declaring explicitly scalameter-core dependency to my build (it was a transitive dependency)
Note that the test is working properly without the explicit dependency with scalatest only (without scalafix)
I am using SBT 1.8
