### ISSUE TITLE
When used in VSCode scala plugin. throws "java.util.ServiceConfigurationError: scalafix.v1.Rule: Provider scalafix.internal.rule.DisableSyntax not a subtype"

### ISSUE THREAD

**Issue by tribbloid** [scalacenter/scalafix#1484]
This is the full stack trace:

```

[Error - 5:14:59 p.m.] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.util.concurrent.ExecutionException: Boxed Error
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$KeptPromise$.apply(Promise.scala:406)
	at scala.concurrent.Promise$.fromTry(Promise.scala:142)
	at scala.concurrent.Promise$.failed(Promise.scala:128)
	at scala.concurrent.Future$.failed(Future.scala:624)
	at scala.meta.internal.metals.ScalafixProvider.$anonfun$organizeImports$1(ScalafixProvider.scala:95)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more
Caused by: java.util.ServiceConfigurationError: scalafix.v1.Rule: Provider scalafix.internal.rule.DisableSyntax not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.next(JavaCollectionWrappers.scala:38)
	at scala.collection.immutable.List.prependedAll(List.scala:153)
	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1251)
	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1251)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1288)
	at scalafix.internal.v1.Rules$.all(Rules.scala:104)
	at scalafix.v1.RuleDecoder$$anon$1.<init>(RuleDecoder.scala:102)
	at scalafix.v1.RuleDecoder$.decoder(RuleDecoder.scala:101)
	at scalafix.internal.v1.Args.ruleDecoder(Args.scala:254)
	at scalafix.internal.v1.Args.configuredRules(Args.scala:288)
	at scalafix.internal.v1.Args.$anonfun$validate$1(Args.scala:420)
	at metaconfig.Configured.andThen(Configured.scala:45)
	at scalafix.internal.v1.Args.validate(Args.scala:416)
	at scalafix.internal.interfaces.ScalafixArgumentsImpl.evaluate(ScalafixArgumentsImpl.scala:41)
	at scala.meta.internal.metals.ScalafixProvider.$anonfun$scalafixEvaluate$7(ScalafixProvider.scala:303)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.meta.internal.metals.ScalafixProvider.$anonfun$scalafixEvaluate$6(ScalafixProvider.scala:285)
	at scala.util.Success.flatMap(Try.scala:251)
	at scala.meta.internal.metals.ScalafixProvider.scalafixEvaluate(ScalafixProvider.scala:284)
	at scala.meta.internal.metals.ScalafixProvider.$anonfun$organizeImports$1(ScalafixProvider.scala:86)
	... 6 more

```

Any idea what';s the cause or how to fix it?

**Comment by bjaglin** [comment]
@tribbloid any chance we can get your conf? Thanks!
