### ISSUE TITLE
Java 17 issue - Unsupported class file major version 61

### ISSUE THREAD

**Issue by mnd999** [scalacenter/scalafix#1503]
I'm seeing this with Java 17 on Scala 2.12:

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at scala.tools.asm.ClassReader.<init>(ClassReader.java:196)
	at scala.tools.asm.ClassReader.<init>(ClassReader.java:177)
	at scala.tools.asm.ClassReader.<init>(ClassReader.java:163)
	at scala.tools.asm.ClassReader.<init>(ClassReader.java:284)
	at scala.meta.internal.metacp.package$.scala$meta$internal$metacp$package$$readInputStreamToClassNode(package.scala:89)
	at scala.meta.internal.metacp.package$XtensionAsmClassfileOps.toClassNode(package.scala:75)
	at scala.meta.internal.symtab.GlobalSymbolTable.loadSymbol(GlobalSymbolTable.scala:37)
	at scala.meta.internal.symtab.GlobalSymbolTable.info(GlobalSymbolTable.scala:67)
	at scalafix.internal.v1.InternalSemanticDoc.info(InternalSemanticDoc.scala:75)
	at scalafix.internal.v0.LegacySemanticdbIndex.denotation(LegacySemanticdbIndex.scala:79)
	at scalafix.internal.v0.LegacySemanticdbIndex.$anonfun$denotation$2(LegacySemanticdbIndex.scala:84)
```

**Comment by mnd999** [comment]
Still an issue in 0.9.33

**Comment by mlachkar** [comment]
thanks for reporting. Can you please tell me which version of scala 2.12 are you using so I can reproduce the error ?

**Comment by tgodzik** [comment]
Scalameta seems to be using `scala.tools.asm` from the compiler itself, so it might be an unsupported Scala 2.12.x version as @mlachkar suggested.

**Comment by mnd999** [comment]
Yeah, I think you're right. I was on 2.12.13 - 2.12.15 seems to fix the issue.
