### ISSUE TITLE
IllegalArgumentException when printing position in Rewrite

### ISSUE THREAD

**Issue by allanrenucci** [scalacenter/scalafix#151]
```scala
logger.debug(tok.pos)
```
fails with the following stack trace:
```
[info] SemanticTests:
[info] - checkSyntax/NoXml.source: protect curly brace *** FAILED *** (818 milliseconds)
[info]   java.lang.IllegalArgumentException: /var/folders/xy/999l9mw10w93cn21215b16gm0000gn/T/paradise3834616381056301353.scala is not relative to /Users/renucci/Documents/Projects/scalafix
[info]   at scala.meta.internal.io.CommonPathIO.unresolve(CommonPathIO.scala:29)
[info]   at scala.meta.internal.io.CommonPathIO.unresolve$(CommonPathIO.scala:23)
[info]   at scala.meta.internal.io.PathIO$.unresolve(PathIO.scala:6)
[info]   at scala.meta.io.AbsolutePath.toRelative(AbsolutePath.scala:14)
[info]   at scala.meta.io.AbsolutePath.toRelative(AbsolutePath.scala:13)
[info]   at scala.meta.inputs.Input$File.toString(Input.scala:57)
[info]   at java.lang.String.valueOf(String.java:2994)
[info]   at java.lang.StringBuilder.append(StringBuilder.java:131)
[info]   at scala.StringContext.standardInterpolator(StringContext.scala:125)
[info]   at scala.StringContext.s(StringContext.scala:95)
[info]   ...
```

**Comment by olafurpg** [comment]
I believe this got fixed in #165 when the tests got reorganized. This is yet another sample where exceptions should be replaced with stronger types IMO https://github.com/scalameta/scalameta/issues/821 AbsolutePath.relativeTo(AbsolutePath) is not a safe operation so it should not return a RelativePath.
