### ISSUE TITLE
sbt-scalafix (sometimes) crashes on Linux

### ISSUE THREAD

**Issue by ahoy-jon** [scalacenter/scalafix#2073]
We have this issue on Linux, but not in IntelliJ-sbt-shell on the same machine.

Does that speak to anyone?

Cheers, 
Jonathan

* Scala 3.5.0
* Sbt-Scalafix 0.12.1
```
[error] scalafix.internal.v1.FileException: unexpected error processing file  .../WarpScriptTest.scala
[error] Caused by: java.nio.file.NoSuchFileException: .../WarpScript.class
[error] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[error] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[error] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[error] 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
[error] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
[error] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
[error] 	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
[error] 	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
[error] 	at scala.meta.internal.classpath.UncompressedClassfile.openInputStream(ClasspathElement.scala:57)
[error] 	at scala.meta.internal.metacp.package$XtensionAsmClassfileOps$.toClassNode$extension(package.scala:74)
[error] 	at scala.meta.internal.symtab.GlobalSymbolTable.loadSymbol(GlobalSymbolTable.scala:37)
[error] 	at scala.meta.internal.symtab.GlobalSymbolTable.info(GlobalSymbolTable.scala:67)
[error] 	at scalafix.internal.v1.InternalSemanticDoc.info(InternalSemanticDoc.scala:75)
[error] 	at scalafix.v1.SemanticDocument.info(SemanticDocument.scala:39)
[error] 	at scalafix.v1.Symbol.info(Symbol.scala:24)
[error] 	at fix.NamedParamOrder$$anonfun$fix$NamedParamOrder$$getPatch$1.applyOrElse(NamedParamOrder.scala:66)
[error] 	at fix.NamedParamOrder$$anonfun$fix$NamedParamOrder$$getPatch$1.applyOrElse(NamedParamOrder.scala:34)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
[error] 	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
[error] 	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$3$.apply(Api.scala:32)
[error] 	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1(SimpleTraverser.scala:5)
[error] 	at scala.meta.transversers.SimpleTraverser.$anonfun$apply$1$adapted(SimpleTraverser.scala:5)
[error] 	at scala.collection.immutable.List.foreach(List.scala:334)
[error] 	at scala.meta.transversers.SimpleTraverser.apply(SimpleTraverser.scala:5)
[error] 	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$3$.apply(Api.scala:33)
[error] 	at scala.meta.transversers.Api$XtensionCollectionLikeUI.collect(Api.scala:36)
[error] 	at fix.NamedParamOrder.fix$NamedParamOrder$$getPatch(NamedParamOrder.scala:34)
[error] 	at fix.NamedParamOrder.fix(NamedParamOrder.scala:31)
[error] 	at scalafix.internal.v1.Rules.$anonfun$semanticPatch$1(Rules.scala:78)
[error] 	at scala.collection.immutable.List.map(List.scala:251)
[error] 	at scalafix.internal.v1.Rules.semanticPatch(Rules.scala:76)
[error] 	at scalafix.internal.v1.MainOps$.getPatchesAndDiags(MainOps.scala:306)
[error] 	at scalafix.internal.v1.MainOps$.unsafeHandleFile(MainOps.scala:256)
[error] (scalafixAll) scalafix.sbt.ScalafixFailed: UnexpectedError
[error] Total time: 172 s (02:52), completed 17 sept. 2024, 09:46:38
```

**Comment by ahoy-jon** [comment]
It was always the same type of trace on the same machine. We suspect it was some competition between compilers (intellIj + console) using .bloop. The bug is not reappearing for now.
