### ISSUE TITLE
RemoveUnusedImports strange exception

### ISSUE THREAD

**Issue by btd** [scalacenter/scalafix#217]
Hi there, i just upgraded project to 2.12 and noticed tons of unused imports warnings. After applying scalafix:

```
> admin/scalafix RemoveUnusedImports
[info] Compiling 7 Scala sources to /mnt/d/Projects/InGo/WebApp/common-webapp/target/scala-2.12/classes...
[error] failed to generate semanticdb for /mnt/d/Projects/InGo/WebApp/common-webapp/src/main/scala/ingo/webapp/Main.scala:
[error] org.scalameta.invariants.InvariantFailedException: invariant failed:
[error] when verifying ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)).==('\"')
[error] found that ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)) is not equal to '\"'
[error] where ScalametaTokenizer = scala.meta.internal.tokenizers.ScalametaTokenizer@650d1ea
[error]         at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
...
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] one error found
[info] Done packaging.
[info] Running scalafix --config /mnt/d/Projects/InGo/WebApp/.scalafix.conf --no-sys-exit -i --sourceroot /mnt/d/Projects/InGo/WebApp --classpath /mnt/d/Projects/InGo/WebApp/liquibase/target/scala-2.12/classes
scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (common/compile:scalafix) scalafix.cli.Cli$NonZeroExitCode: Got exit code InvalidCommandLineOption=8
[error] (commonWebApp/compile:compileIncremental) Compilation failed

```
Not sure really what this could mean. 

This is with sbt-scalafix 0.4.2, scala 2.12.2, sbt 0.13.13

**Comment by btd** [comment]
It looks it is issue because of crlf ending at windows. This is known bug in scalameta parser. Closing.

**Comment by olafurpg** [comment]
Thank you for reporting, and investigating! Can you please link to the scalameta issue? We may be able to prioritize it.

**Comment by btd** [comment]
I think it is this [one](https://github.com/scalameta/scalameta/issues/911). For me issue disapeared after i fixed all to \n
