### ISSUE TITLE
ExplicitResultType Rule and anonymous classes

### ISSUE THREAD

**Issue by allanrenucci** [scalacenter/scalafix#377]
The following code snippet
```scala
class ExplicitResultType {
  trait Foo
  implicit val foo = new Foo {}
}
```
is rewritten as follow under the `ExplicitResultType` rule
```scala
class ExplicitResultType {
  trait Foo
  implicit val foo: _root_.scala.AnyRef with _empty_.ExplicitResultType#Foo {} = new Foo {}
}
```
We might be able to strip `AnyRef` off the type in case it is an anonymous class

**Comment by allanrenucci** [comment]
For the same code snippet, if I have `ExplicitResultTypes.unsafeShortenNames = true` in `.scalafix.conf`, then it fails with a match error:
```scala
scala.MatchError:  (of class org.langmeta.semanticdb.Symbol$None$)
	at scalafix.internal.util.SymbolOps$.toTermRef(SymbolOps.scala:36)
	at scalafix.internal.util.SymbolOps$.toTermRef(SymbolOps.scala:37)
	at scalafix.internal.util.SymbolOps$.toImporter(SymbolOps.scala:47)
	at scalafix.internal.patch.ImportPatchOps$.$anonfun$superNaiveImportPatchToTokenPatchConverter$13(ImportPatchOps.scala:117)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.immutable.List.flatMap(List.scala:352)
	at scalafix.internal.patch.ImportPatchOps$.superNaiveImportPatchToTokenPatchConverter(ImportPatchOps.scala:111)
	at scalafix.patch.Patch$.semanticApply(Patch.scala:186)
	at scalafix.patch.Patch$.apply(Patch.scala:154)
	at scalafix.rule.Rule.apply(Rule.scala:86)
	at scalafix.rule.Rule.apply(Rule.scala:83)
	at scalafix.rule.Rule.apply(Rule.scala:73)
	at scalafix.cli.CliRunner.unsafeHandleInput(CliRunner.scala:121)
	at scalafix.cli.CliRunner.safeHandleInput(CliRunner.scala:164)
	at scalafix.cli.CliRunner.$anonfun$run$1(CliRunner.scala:74)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
```
Running scalafix from sbt, plugin version `0.5.2`

**Comment by olafurpg** [comment]
Thanks for reporting! I am unable to reproduce with the latest master, the rewrite emits

```scala
implicit val foo: _root_.test.explicitResultTypes.ExplicitResultType#Foo = new Foo {}
```

as expected :)
