### ISSUE TITLE
 java.lang.ExceptionInInitializerError for scalafix 0.5.8 / jgit crash when sbt-scalafix starts

### ISSUE THREAD

**Issue by mielientiev** [scalacenter/scalafix#575]
I got next exception while trying to load sbt multi project with scalafix plugin 
`addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.8")`

```
[error] java.lang.ExceptionInInitializerError
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:348)
[error]         at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error]         at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error]         at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error]         at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:415)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
[error]         at scala.collection.generic.Growable.loop$1(Growable.scala:54)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
[error]         at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:147)
[error]         at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:143)
[error]         at scala.collection.immutable.List.$plus$plus(List.scala:207)
[error]         at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:54)
[error]         at sbt.internal.Load$.loadPlugins(Load.scala:1267)
[error]         at sbt.internal.Load$.loadPluginDefinition(Load.scala:1212)
[error]         at sbt.internal.Load$.buildPlugins(Load.scala:1191)
[error]         at sbt.internal.Load$.plugins(Load.scala:1174)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:683)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:683)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:677)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:158)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:223)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error]         at sbt.internal.Load$.loadAll(Load.scala:555)
[error]         at sbt.internal.Load$.loadURI(Load.scala:485)
[error]         at sbt.internal.Load$.load(Load.scala:464)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:253)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.apply(Load.scala:253)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:707)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:707)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:680)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error]         at sbt.State$$anon$1.process(State.scala:248)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:136)
[error]         at sbt.MainLoop$.run(MainLoop.scala:129)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error]         at sbt.StandardMain$.runManaged(Main.scala:113)
[error]         at sbt.xMain.run(Main.scala:76)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: org.eclipse.jgit.api.errors.NoHeadException: No HEAD exists and no explicit starting revision was specified
[error]         at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:152)
[error]         at scalafix.internal.sbt.JGitCompletion.<init>(JGitCompletions.scala:16)
[error]         at scalafix.internal.sbt.ScalafixCompletions$.gitDiffParser(ScalafixCompletions.scala:71)
[error]         at scalafix.internal.sbt.ScalafixCompletions$.parser(ScalafixCompletions.scala:125)
[error]         at scalafix.sbt.ScalafixPlugin$.<init>(ScalafixPlugin.scala:162)
[error]         at scalafix.sbt.ScalafixPlugin$.<clinit>(ScalafixPlugin.scala)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:348)
[error]         at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error]         at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error]         at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error]         at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:415)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
[error]         at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
[error]         at scala.collection.generic.Growable.loop$1(Growable.scala:54)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
[error]         at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:147)
[error]         at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:143)
[error]         at scala.collection.immutable.List.$plus$plus(List.scala:207)
[error]         at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:54)
[error]         at sbt.internal.Load$.loadPlugins(Load.scala:1267)
[error]         at sbt.internal.Load$.loadPluginDefinition(Load.scala:1212)
[error]         at sbt.internal.Load$.buildPlugins(Load.scala:1191)
[error]         at sbt.internal.Load$.plugins(Load.scala:1174)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:683)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:683)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:677)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:477)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:158)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:223)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:539)
[error]         at sbt.internal.Load$.loadAll(Load.scala:555)
[error]         at sbt.internal.Load$.loadURI(Load.scala:485)
[error]         at sbt.internal.Load$.load(Load.scala:464)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:253)
[error]         at sbt.internal.Load$.timed(Load.scala:1343)
[error]         at sbt.internal.Load$.apply(Load.scala:253)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:707)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:707)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:680)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error]         at sbt.State$$anon$1.process(State.scala:248)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:136)
[error]         at sbt.MainLoop$.run(MainLoop.scala:129)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error]         at sbt.StandardMain$.runManaged(Main.scala:113)
[error]         at sbt.xMain.run(Main.scala:76)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ExceptionInInitializerError
```

*scalafix version*: 0.5.8
*sbt version*: 1.0.4 and 1.1.0

this bug was introduced here: https://github.com/scalacenter/scalafix/commit/a1232517

**Comment by MasseGuillaume** [comment]
@mielientiev
nice catch, this is a project without git I assume. I'm creating a hotfix now for this.

**Comment by luksow** [comment]
Hi, the error still occurs if you're working on a project that resides in a directory with fresh (empty) git repo.

**Comment by MasseGuillaume** [comment]
@luksow thank for reporting reopened.

**Comment by olafurpg** [comment]
@luksow what version are you using?

**Comment by luksow** [comment]
@olafurpg 0.5.10

**Comment by olafurpg** [comment]
Is this still an issue?

**Comment by luksow** [comment]
@olafurpg is there a new release? Because I encountered it again with 0.5.10 yesterday.

**Comment by olafurpg** [comment]
There hasn't been any fix yet so I suspect it's still relevant. Can you take a look @MasseGuillaume ?

**Comment by olafurpg** [comment]
I'm unable to reproduce this error in the latest commit of sbt-scalafix.
