### ISSUE TITLE
Crash resulting in warning

### ISSUE THREAD

**Issue by dragos** [scalacenter/scalafix#672]
This code seems to reliably crash scalafix (or scalameta):

```
package entities

import java.util.UUID

trait Entity {
  self =>

  val id: UUID
  override def hashCode(): Int = id.hashCode
  override def equals(obj: scala.Any): Boolean =
    obj != null && obj.getClass == self.getClass && obj.asInstanceOf[SomeEntity].id == id
}

case class SomeEntity(id: UUID, resources: Map[String, String] = Map()) extends Entity
```

I'm sure it can be minimized further, but it's probably already a good start. Using scalafix `0.6.0-M1` and Scala 2.12.4.

```
> compile
[info] Compiling 1 Scala source to /Users/dragos/workspace/triplequote/tests/hydra-test/target/scala-2.12/classes...
[warn] failed to generate semanticdb for /Users/dragos/workspace/triplequote/tests/hydra-test/src/main/scala/entities/Entities.scala:
[warn] java.lang.AssertionError: assertion failed
[warn]  at scala.Predef$.assert(Predef.scala:204)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.$anonfun$tryFindMtree$4(DocumentOps.scala:209)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.$anonfun$tryFindMtree$4$adapted(DocumentOps.scala:206)
[warn]  at scala.collection.immutable.List.foreach(List.scala:389)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.add$1(DocumentOps.scala:206)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.saveDenotation$1(DocumentOps.scala:215)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.success$1(DocumentOps.scala:225)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.tryMstart$1(DocumentOps.scala:244)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.tryFindMtree(DocumentOps.scala:339)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:481)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1295)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1306)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1295)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2484)
[warn]  at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2484)
[warn]  at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1296)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1306)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1295)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1227)
[warn]  at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
[warn]  at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1215)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1340)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2498)
[warn]  at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
[warn]  at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2498)
[warn]  at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
[warn]  at scala.reflect.internal.Trees.traverseComponents$1(Trees.scala:1244)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1342)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1219)
[warn]  at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
[warn]  at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1215)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1340)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:157)
[warn]  at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2498)
[warn]  at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
[warn]  at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2498)
[warn]  at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
[warn]  at scala.reflect.internal.Trees.itraverse(Trees.scala:1338)
[warn]  at scala.reflect.internal.Trees.itraverse$(Trees.scala:1212)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[warn]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument$traverser$4$.traverse(DocumentOps.scala:483)
[warn]  at scala.meta.internal.semanticdb.scalac.DocumentOps$XtensionCompilationUnitDocument.toDocument(DocumentOps.scala:486)
[warn]  at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:58)
[warn]  at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
[warn]  at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
[warn]  at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:400)
[warn]  at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:400)
[warn]  at scala.collection.Iterator.foreach(Iterator.scala:929)
[warn]  at scala.collection.Iterator.foreach$(Iterator.scala:929)
[warn]  at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[warn]  at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:400)
[warn]  at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:66)
[warn]  at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1452)
[warn]  at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1436)
[warn]  at scala.tools.nsc.Global$Run.compileSources(Global.scala:1429)
[warn]  at scala.tools.nsc.Global$Run.compile(Global.scala:1545)
[warn]  at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
[warn]  at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
[warn]  at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
[warn]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[warn]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[warn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[warn]  at java.lang.reflect.Method.invoke(Method.java:498)
[warn]  at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
[warn]  at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
[warn]  at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
[warn]  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
[warn]  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
[warn]  at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
[warn]  at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
[warn]  at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
[warn]  at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
[warn]  at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[warn]  at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
[warn]  at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
[warn]  at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
[warn]  at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
[warn]  at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
[warn]  at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
[warn]  at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
[warn]  at sbt.inc.Incremental$.compile(Incremental.scala:71)
[warn]  at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
[warn]  at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
[warn]  at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
[warn]  at sbt.Compiler$.compile(Compiler.scala:155)
[warn]  at sbt.Compiler$.compile(Compiler.scala:141)
[warn]  at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:886)
[warn]  at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:877)
[warn]  at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:875)
[warn]  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[warn]  at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[warn]  at sbt.std.Transform$$anon$4.work(System.scala:63)
[warn]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[warn]  at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[warn]  at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[warn]  at sbt.Execute.work(Execute.scala:237)
[warn]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[warn]  at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[warn]  at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[warn]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[warn]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[warn]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[warn]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[warn]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[warn]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[warn]  at java.lang.Thread.run(Thread.java:748)
[warn] one warning found
```

**Comment by olafurpg** [comment]
Thanks for reporting! I am unable to reproduce on that input with the latest version of semanticdb-scalac using the default compiler settings. The latest scalafix release v0.6.0-M1 uses a bit older version with non-default settings.

I aim to have a new scalafix milestone out this week that completes the migration to the latest default settings. Let's see if the problem persists then.

**Comment by olafurpg** [comment]
PS. `-P:semanticdb:failures:ignore` can be used to silence error messages from the compiler plugin.

**Comment by olafurpg** [comment]
Please reopen in  https://github.com/scalameta/scalameta/ if you are able to reproduce. Scalafix recently upgraded the scalameta dependency from a several month version so it might already be fixed.
