### ISSUE TITLE
InvalidWireTypeException when trying to run scalafix on a maven project

### ISSUE THREAD

**Issue by gfjalar** [scalacenter/scalafix#726]
Hey, I'm having some trouble trying to get `scalafix` to work in a maven, multi-module project.

Versions used:
- `scalafix`: `0.5.10`
- `scala`: `2.11.12`
- `semanticdb-scalac_2.11.12`: `3.7.4`
- `scala-maven-plugin`: `3.3.2`
- `java`: `1.8.0_152`

Compilation step goes on as expected and generates target with `META-INF` dirs under `classes` and `test-classes`. Then when trying to do `scalafix -r RemoveUnusedImportes --verbose`, I'm encountering the following error:
```
Automatic classpath=FULL_PATH_TO_THE_MODULE_DIRECTORY/target/classes:FULL_PATH_TO_THE_MODULE_DIRECTORY/target/test-classes
error: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:591)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipMessage(CodedInputStream.java:650)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:581)
	at org.langmeta.internal.semanticdb.schema.ResolvedName.mergeFrom(ResolvedName.scala:67)
	at org.langmeta.internal.semanticdb.schema.ResolvedName.mergeFrom(ResolvedName.scala:11)
	at com.trueaccord.scalapb.LiteParser$.readMessage(LiteParser.scala:15)
	at org.langmeta.internal.semanticdb.schema.Document.mergeFrom(Document.scala:101)
	at org.langmeta.internal.semanticdb.schema.Document.mergeFrom(Document.scala:11)
	at com.trueaccord.scalapb.LiteParser$.readMessage(LiteParser.scala:15)
	at org.langmeta.internal.semanticdb.schema.Database.mergeFrom(Database.scala:44)
	at org.langmeta.internal.semanticdb.schema.Database.mergeFrom(Database.scala:11)
	at com.trueaccord.scalapb.LiteParser$.parseFrom(LiteParser.scala:9)
	at com.trueaccord.scalapb.GeneratedMessageCompanion.parseFrom(GeneratedMessageCompanion.scala:178)
	at com.trueaccord.scalapb.GeneratedMessageCompanion.parseFrom$(GeneratedMessageCompanion.scala:178)
	at org.langmeta.internal.semanticdb.schema.Database$.parseFrom(Database.scala:71)
	at com.trueaccord.scalapb.GeneratedMessageCompanion.parseFrom(GeneratedMessageCompanion.scala:194)
	at com.trueaccord.scalapb.GeneratedMessageCompanion.parseFrom$(GeneratedMessageCompanion.scala:194)
	at org.langmeta.internal.semanticdb.schema.Database$.parseFrom(Database.scala:71)
	at org.langmeta.internal.semanticdb.vfs.Database.$anonfun$toSchema$1(Database.scala:22)
```

Thanks in advance for your help in solving the issue.

**Comment by olafurpg** [comment]
Thanks for reporting! This is expected if you use semanticdb-scala 3.x, scalafix v0.5.10 requires semanticdb-scalac 2.1.7. I hope to have v0.6 final out in the coming weeks that upgrades to 3.x.

**Comment by olafurpg** [comment]
Whoops, I see the docs for maven installation point to 2.1.7. This should be updated https://scalacenter.github.io/scalafix/docs/users/installation#maven

**Comment by gfjalar** [comment]
Thanks, it worked :) Facing some OOMs now, but only when trying to scalafix the entire project. Works like a charm for single modules.

Btw, for the maven installation doc, you could also suggest adding a maven profile with semanticdb set up like so:
```
<profile>
  <id>scalafix</id>
  <build>
    <plugins>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <configuration>
          <compilerPlugins>
            <compilerPlugin>
              <groupId>org.scalameta</groupId>
              <artifactId>semanticdb-scalac_${scala.version}</artifactId>
              <version>${semanticdb.version}</version>
            </compilerPlugin>
          </compilerPlugins>
          <addScalacArgs>-Yrangepos|-Ywarn-unused-import|-Ywarn-unused</addScalacArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</profile>
```

**Comment by olafurpg** [comment]
Cool, I am working on the OOM errors as we speak :) Currently scalafix loads up all *.semanticdb files in memory but in the next v0.6 release it will load one file, which should significantly reduce memory pressure for larger projects.

> Btw, for the maven installation doc, you could also suggest adding a maven profile with semanticdb set up like so:

That's a great idea, would you be tempted to submit a PR? The installation instructions are written in markdown here https://github.com/scalacenter/scalafix/blob/16aaf9c4d2c038d81e7607ff267b5b4d7622e857/website/src/main/tut/docs/users/installation.md

**Comment by gfjalar** [comment]
That's awesome! Can't wait!

Sure :) Though, I'll probably get to it during the weekend the earliest.

**Comment by gfjalar** [comment]
Weekend came early this week 😜 

Created the PR: https://github.com/scalacenter/scalafix/pull/732

AppVeyor test failed. However, it's not related to the docs change:
```
[info]   java.nio.file.FileSystemException: C:\Users\appveyor\AppData\Local\semanticdb\cache\3.7.4\rt-CE076AE93B691787B65675073EDA8962.jar: The process cannot access the file because it is being used by another process.
```

Also, I wasn't sure if I'm to change `scalametaVersion` property, but you can comment on that in the PR.

**Comment by olafurpg** [comment]
Fixed in #732, thanks @gfjalar for updating docs!
