### ISSUE TITLE
StackOverflowError on big file

### ISSUE THREAD

**Issue by joan38** [scalacenter/scalafix#729]
Running scalafix on https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/server/KafkaConfig.scala
Leads to:
```
> ./scalafmt core/src/main/scala/kafka/server/KafkaConfig.scala 
Exception in thread "main" java.lang.StackOverflowError
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
...
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$TermSelectImpl.name(Trees.scala:55)
	at scala.meta.Term$Select$.unapply(Trees.scala:55)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
...
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
	at scala.meta.transversers.Api$XtensionCollectionLikeUI$traverser$4$.apply(Api.scala:31)
	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
```

And this is the same with scalafmt.

The workaround is: `scalafix --exclude=KafkaConfig.scala`

**Comment by olafurpg** [comment]
Thanks for reporting! I have encountered the same issue on that exact file, there is workaround except to increase the stack size to match the size of this expression here https://github.com/apache/kafka/blob/a5318722c74ec0279a2e831e93e4164d9adcb8a1/core/src/main/scala/kafka/server/KafkaConfig.scala#L763-L978

**Comment by joan38** [comment]
Ok I see thanks
