### ISSUE TITLE
 java.lang.UnsupportedOperationException loading old SemanticdbIndex

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#752]
to reproduce

setup and run scalafix with 0.5.9:

```
sbt new scalacenter/scalafix.g8
cd scalafix
sbt tests/test
```

bump to 0.6.0-M9

result:

```
[info] Playground:
[info] fix.Playground *** ABORTED ***
[info]   java.lang.UnsupportedOperationException:
[info]   at scalafix.v0.SemanticdbIndex$.load(SemanticdbIndex.scala:79)
[info]   at fix.Playground.<init>(Playground.scala:9)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:443)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   ...
```

expected:

it should recompile and run the test normally.

**Comment by olafurpg** [comment]
Fix in the g8 template here https://github.com/scalacenter/scalafix.g8/pull/6
