### ISSUE TITLE
ExplicitResultTypes error running on slick

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#789]
```
> slick/scalafix ExplicitResultTypes
scalafix.internal.util.PrettyType$TypeToTreeError: SymbolInformation(scala/package.Iterable#,SCALA,TYPE,0,Iterable,TypeSignature(Some(Scope(List(scala/package.Iterable#[A]),List())),TypeRef(Empty,scala/collection/Iterable#,List(TypeRef(Empty,scala/package.Iterable#[A],List()))),TypeRef(Empty,scala/collection/Iterable#,List(TypeRef(Empty,scala/package.Iterable#[A],List())))),List(),PublicAccess())
	at scalafix.internal.util.PrettyType.fail(PrettyType.scala:421)
	at scalafix.internal.util.PrettyType.toTypeRef(PrettyType.scala:488)
	at scalafix.internal.util.PrettyType.toType(PrettyType.scala:517)
	at scalafix.internal.util.PrettyType$.toType(PrettyType.scala:36)
	at scalafix.internal.rule.ExplicitResultTypes.unsafeToType(ExplicitResultTypes.scala:102)
	at scalafix.internal.rule.ExplicitResultTypes.toType(ExplicitResultTypes.scala:112)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$2(ExplicitResultTypes.scala:131)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$1(ExplicitResultTypes.scala:130)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.defnType$1(ExplicitResultTypes.scala:129)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$9(ExplicitResultTypes.scala:152)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$7(ExplicitResultTypes.scala:149)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.$anonfun$fix$5(ExplicitResultTypes.scala:145)
	at scala.Option.flatMap(Option.scala:171)
	at scalafix.internal.rule.ExplicitResultTypes.scalafix$inter
```

Seems like `TYPE` kinds are not handled in `toTypeRef` 🤔

**Comment by olafurpg** [comment]
Most likely fixed in #989
