### ISSUE TITLE
failed to generate semanticdb

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#790]
```
[warn] failed to generate semanticdb for <elided>:
[warn] java.lang.ArrayIndexOutOfBoundsException: 870
[warn] 	at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:144)
[warn] 	at scala.meta.internal.parsers.ScalametaParser$$anon$189.apply(ScalametaParser.scala:3445)
[warn] 	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
[warn] 	at scala.meta.internal.semanticdb.scalac.ParseOps$XtensionCompilationUnitSource.toSource(ParseOps.scala:11)
[warn] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toScalaTextDocument(TextDocumentOps.scala:161)
[warn] 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:50)
[warn] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:59)
[warn] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:65)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
[warn] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[warn] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[warn] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[warn] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
[warn] 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:75)
[warn] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
[warn] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
[warn] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
[warn] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
[warn] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[warn] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[warn] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[warn] 	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
[warn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[warn] 	at java.lang.reflect.Method.invoke(Method.java:498)
[warn] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[warn] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[warn] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[warn] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[warn] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[warn] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[warn] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[warn] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[warn] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[warn] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[warn] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[warn] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[warn] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[warn] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[warn] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[warn] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[warn] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[warn] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[warn] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[warn] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[warn] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[warn] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[warn] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[warn] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1443)
[warn] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1417)
[warn] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[warn] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[warn] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[warn] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[warn] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[warn] 	at sbt.Execute.work(Execute.scala:272)
[warn] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[warn] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[warn] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[warn] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[warn] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[warn] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[warn] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[warn] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[warn] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olafurpg** [comment]
Thanks for reporting! This is a semanticdb-scalac error. You can work around the error by adding the scalacOption `-P:semanticdb:failures:warning`. See docs on the flags here https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb3/guide.md#scalac-compiler-plugin

**Comment by olafurpg** [comment]
This issue should be reported to scalameta/scalameta. It would be great to have a reproduction, even if a large OSS build to clone and compile. Without more information it's difficult to address this otherwise.

**Comment by joan38** [comment]
Got bitten by this one. Is there a ticket in scalameta?
