### ISSUE TITLE
Using tutorial project with sbt 1.3.0-RC1 doesn't work

### ISSUE THREAD

**Issue by RCMartins** [scalacenter/scalafix#964]
git clone https://github.com/olafurpg/named-literal-arguments.git
cd named-literal-arguments/scalafix
sbt tests/test
`<everything works has expected>`
echo "sbt.version = 1.3.0-RC1" > project/build.properties
sbt tests/test
```
[info] RuleSuite:
[info] fix.RuleSuite *** ABORTED ***
[info]   java.lang.RuntimeException: Failed to load resource scalafix-testkit.properties
[info]   at scala.sys.package$.error(package.scala:30)
[info]   at scalafix.testkit.TestkitProperties$.loadFromResources(TestkitProperties.scala:84)
[info]   at scalafix.testkit.SemanticRuleSuite.<init>(SemanticRuleSuite.scala:23)
[info]   at fix.RuleSuite.<init>(RuleSuite.scala:5)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:443)
[info]   ...
```

Also tried to update the sbt-scalafix version in project/plugins.sbt from `0.6.0-M19` to `0.9.5`, but still got the same error.
It works fine with sbt 1.2.8

**Comment by olafurpg** [comment]
Thanks for reporting! I have updated the example repo to sbt 1.3.0-RC1. The error is caused by the new classloader layering policy. I hope the change the default to ScalaLibrary or Flat before 1.3.0
